### ISSUE TITLE
Seperate images/masks from one node

### ISSUE THREAD

**Issue by Gavr728** [neverbiasu/ComfyUI-SAM2#11]
I'm trying to get separate images/masks for every part of the prompt but getting combined picture instead. From what I saw in the original repo, there were supposed to be multiple images 
![image](https://github.com/user-attachments/assets/07f37be9-a24c-4df2-afb7-8c229c9af313)

**Comment by neverbiasu** [comment]
I don't know if I got ur words, u mean it should output images' amount should be equal with the amount of prompts u provide.

**Comment by Gavr728** [comment]
> I don't know if I got ur words, u mean it should output images' amount should be equal with the amount of prompts u provide.

Exactly, instead I get one picture every time. Tried with different delimiters.

**Comment by neverbiasu** [comment]
it's my neglect, didn't consider this. The code might be enhanced in future work, or u can wait SAM2-WebUI
