### ISSUE TITLE
Conflicting nodes

### ISSUE THREAD

**Issue by mesbahmilad** [neverbiasu/ComfyUI-SAM2#12]
The package is using the same node names as https://github.com/storyicon/comfyui_segment_anything

This is very confusing when loading existing workflows that have been using that package and not knowing which package to install. Installing both package breaks the workflow and the nodes are no longer functional.

**Comment by aleph65** [comment]
thank you SO MUCH. this helped resolve a major issue lots of people seem to be having. @mesbahmilad
