### ISSUE TITLE
please push the fixes for a few bugs:

### ISSUE THREAD

**Issue by donlee1** [neverbiasu/ComfyUI-SAM2#13]
bug 1: "axes don't match array" issue:

@Yuliuchengyin You should delete the squeeze(0) in SAM2ImagePredictor.predict (line 280 - line 282 in ComfyUI-SAM2/sam2/sam2_image_predictor.py). Then it will works!

bug 2: "RuntimeError: No available kernel. Aborting execution.":
I solved this issue by adding some lines after [L22](https://github.com/facebookresearch/segment-anything-2/blob/86827e2fbae8a293f61d51caa70a4b0602c04454/sam2/modeling/sam/transformer.py#L22) in sam2\modeling\sam\transformer.py

USE_FLASH_ATTN = False
MATH_KERNEL_ON = True
OLD_GPU = True

**Comment by neverbiasu** [comment]
thx, fix it now
