### ISSUE TITLE
torch==2.3.1？？？？

### ISSUE THREAD

**Issue by hben35096** [neverbiasu/ComfyUI-SAM2#16]
What makes you write this? Don't you know that this will cause the entire ComfyUI environment to be redeployed?

**Comment by hben35096** [comment]
Name: timm
Version: 0.9.5

Name: addict
Version: 2.4.0

Name: yapf
Version: 0.40.2

Name: torch
Version: 2.1.1

Name: torchvision
Version: 0.16.1

Name: numpy
Version: 1.24.1

Name: tqdm
Version: 4.64.1

Name: hydra-core
Version: 1.3.2

Name: iopath
Version: 0.1.10

Name: pillow
Version: 10.3.0

Name: matplotlib
Version: 3.6.3

Name: opencv-python
Version: 4.8.1.78

---

I completely removed the version information of the requirements.txt file, the result after installation, and this seems to be no problem

**Comment by neverbiasu** [comment]
I feel so bad that my requirements broke your environment, now it works.
