### ISSUE TITLE
AttributeError: 'ImageEncoder' object has no attribute 'img_size'

### ISSUE THREAD

**Issue by BenDes21** [neverbiasu/ComfyUI-SAM2#22]
<img width="638" alt="Untictled" src="https://github.com/user-attachments/assets/79896c0e-7fee-4cbd-8010-f70f0c53aac3">

Any solution ?

**Comment by Celtmant** [comment]
same problem

**Comment by Celtmant** [comment]
> <img alt="Untictled" width="638" src="https://private-user-images.githubusercontent.com/153294763/364696144-79896c0e-7fee-4cbd-8010-f70f0c53aac3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1NTM5NDEsIm5iZiI6MTcyNTU1MzY0MSwicGF0aCI6Ii8xNTMyOTQ3NjMvMzY0Njk2MTQ0LTc5ODk2YzBlLTdmZWUtNGNiZC04MDEwLWY3MGYwYzUzYWFjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxNjI3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzliNjhkMzc2Zjc2ZWY0NzYyZTMxNDE5ZjAyZmJmOGI0M2ZiMjlhNDY1Zjc4ZDVlOWIzMWJjNjZlMDNhYTcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.86053J0Bt4VPvcBIKF8NG6LTjR_fa4PAfcGqxgYUFYY">
> Any solution ?

In general, the problem is in Sam 2, I switched to the Sam 1 loader and everything works on the model from 2 gig,

**Comment by neverbiasu** [comment]
Could u show me your fully traceback?

**Comment by SaintLandline** [comment]
```
!!! Exception during processing!!! 'ImageEncoder' object has no attribute 'img_size'
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 325, in main
    (images, masks) = sam_segment(
                      ^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 240, in sam_segment
    predictor = SamPredictorHQ(sam_model, sam_is_hq)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\predictor.py", line 22, in __init__
    super().__init__(sam_model=sam_model)
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\segment_anything\predictor.py", line 31, in __init__
    self.transform = ResizeLongestSide(sam_model.image_encoder.img_size)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ImageEncoder' object has no attribute 'img_size'
```

**Comment by coollofty** [comment]
same problem, who solved?

**Comment by Maelstrom2014** [comment]
same problem

**Comment by neverbiasu** [comment]
U r using `comfyui_segment_anything` node, I'll change our nodes name to distinguish it from the former.

**Comment by coollofty** [comment]
> U r using `comfyui_segment_anything` node, I'll change our nodes name to distinguish it from the former.

It's not a problem with the name. I changed the name in the code and confirmed that the wrong node was not used, but the error still persists

```
NODE_CLASS_MAPPINGS = {
    'SAM2ModelLoader (sam2)': SAM2ModelLoader,
    'GroundingDinoModelLoader (sam2)': GroundingDinoModelLoader,
    'GroundingDinoSAMSegment (sam2)': GroundingDinoSAMSegment,
    'InvertMask (sam2)': InvertMask,
    "IsMaskEmpty (sam2)": IsMaskEmptyNode,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    'SAM2ModelLoader': 'SAM2 Model Loader',
    'GroundingDinoModelLoader': 'Grounding Dino Model Loader',
    'GroundingDinoSAMSegment': 'Grounding Dino SAM Segment',
    'InvertMask': 'Invert Mask',
    "IsMaskEmpty": "Is Mask Empty",
}
```

> Error during runtime:
> 
> Traceback (most recent call last):
>   File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SAM2\node.py", line 311, in main
>     (images, masks) = sam_segment(
>                       ^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SAM2\node.py", line 224, in sam_segment
>     predictor = SAM2ImagePredictor(sam_model)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SAM2\sam2\sam2_image_predictor.py", line 41, in __init__
>     self._transforms = SAM2Transforms(
>                        ^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SAM2\sam2\utils\transforms.py", line 28, in __init__
>     self.transforms = torch.jit.script(
>                       ^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_script.py", line 1432, in script
>     return _script_impl(
>            ^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_script.py", line 1146, in _script_impl
>     return torch.jit._recursive.create_script_module(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 556, in create_script_module
>     concrete_type = get_module_concrete_type(nn_module, share_types)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 505, in get_module_concrete_type
>     concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 437, in get_or_create_concrete_type
>     concrete_type_builder = infer_concrete_type_builder(nn_module)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 286, in infer_concrete_type_builder
>     sub_concrete_type = get_module_concrete_type(item, share_types)
>                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 505, in get_module_concrete_type
>     concrete_type = concrete_type_store.get_or_create_concrete_type(nn_module)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 437, in get_or_create_concrete_type
>     concrete_type_builder = infer_concrete_type_builder(nn_module)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 397, in infer_concrete_type_builder
>     attr_type, inferred = infer_type(name, value)
>                           ^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_recursive.py", line 236, in infer_type
>     attr_type = torch._C._jit_try_infer_type(item)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\annotations.py", line 492, in try_ann_to_type
>     scripted_class = torch.jit._script._recursive_compile_class(ann, loc)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\jit\_script.py", line 1602, in _recursive_compile_class
>     rcb = _jit_internal.createResolutionCallbackForClassMethods(obj)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\_jit_internal.py", line 473, in createResolutionCallbackForClassMethods
>     captures.update(get_type_hint_captures(fn))
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\python_embeded\Lib\site-packages\torch\_jit_internal.py", line 387, in get_type_hint_captures
>     raise OSError(
> OSError: Failed to get source for <function Enum._generate_next_value_ at 0x00000128B33F9080> using inspect.getsource

**Comment by drake7707** [comment]
Having the same problem:
```
2024-09-24 13:16:45.202028 #28 [GroundingDinoModelLoader (segment anything)]: 4.87s
!!! Exception during processing !!! 'ImageEncoder' object has no attribute 'img_size'
Traceback (most recent call last):
  File "/comfyui/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/comfyui/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/custom_nodes/comfyui_segment_anything/node.py", line 325, in main
    (images, masks) = sam_segment(
                      ^^^^^^^^^^^^
  File "/comfyui/custom_nodes/comfyui_segment_anything/node.py", line 240, in sam_segment
    predictor = SamPredictorHQ(sam_model, sam_is_hq)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/comfyui/custom_nodes/comfyui_segment_anything/sam_hq/predictor.py", line 22, in __init__
    super().__init__(sam_model=sam_model)
  File "/opt/conda/lib/python3.11/site-packages/segment_anything/predictor.py", line 31, in __init__
    self.transform = ResizeLongestSide(sam_model.image_encoder.img_size)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ImageEncoder' object has no attribute 'img_size'

```

**Comment by drake7707** [comment]
Oh ok I understand what's going on. I have to uninstall the segment anything so it's a naming issue. Once the nodes use all the nodes from this repo it works.

**Comment by coollofty** [comment]
> Oh ok I understand what's going on. I have to uninstall the segment anything custom nodes so it's a naming issue. Once the nodes use all the nodes from this repo it works.

![screen-capture](https://github.com/user-attachments/assets/b9a3cb3a-ba4c-4175-b009-b1c0ad386a81)

No, it's not you understand..... Look at this workflow, it uses all the nodes from this repo as mentioned above, and I have changed the names of all the nodes, so the nodes won't be used incorrectly, but the errors same

**Comment by drake7707** [comment]
I had both `ComfyUI-segment-anything-2` and `comfyui_segment_anything` in my custom nodes. Both of them have naming collisions with this repo. When I moved them out of my custom_nodes and restarted everything worked
