### ISSUE TITLE
Request changes to dependency requirements files

### ISSUE THREAD

**Issue by hben35096** [neverbiasu/ComfyUI-SAM2#23]
Your dependency requirement file has harmed many people.

**Comment by cnqdztp** [comment]
May I ask why? Haven't tried this yet.

**Comment by neverbiasu** [comment]
> Your dependency requirement file has harmed many people.

Torch version? Could u explain it definitely?

**Comment by hben35096** [comment]
Yes, this is one aspect. If the user's runtime environment has a version of torch that is not equal to 2.3.1 and xformers is installed, after forcing the torch version to 2.3.1, there is a high chance that a conflict will occur with xformers, preventing ComfyUI from starting.

Now, the Manager has placed restrictions on this, avoiding the automatic upgrading or downgrading of torch during installation, thus preventing the aforementioned issue. Therefore, specifying torch==2.3.1 will not cause any harm, but it would appear redundant.

Also, writing numpy>=1.24.4 is not ideal. If the previous runtime environment had numpy<1.24.4, upgrading numpy could lead to the installation of a version that is too high, potentially causing a series of conflicts that prevent ComfyUI from starting. So, certain restrictions are necessary.

**Comment by neverbiasu** [comment]
@hben35096 Thx for your correction, I will modify it. 

- [ ] remove specific torch version.
- [ ] rewrite the version restrictions of numpy.
