### ISSUE TITLE
Visible edge jaggedness, is it common for SAM model？

### ISSUE THREAD

**Issue by Young-Chin** [neverbiasu/ComfyUI-SAM2#24]
As we can see in the pic, there is some visible edge jaggedness(bottom), is it common for the SAM model? 
And, are there any solutions? 

Thx~

![1726631413948](https://github.com/user-attachments/assets/dcd4e097-388c-4888-81a1-f9d8f7f04602)

**Comment by neverbiasu** [comment]
Rarely occurs, what the source of this picture is?

**Comment by Young-Chin** [comment]
The first image is the source image, the other image also appears to have bad clothing edges.

![360946871131137_RMxe_lo1_0](https://github.com/user-attachments/assets/444876cd-7670-484f-b3b6-000ac203c73f)
![6623896295424_fRcz_lo0_0](https://github.com/user-attachments/assets/b9add157-2cc1-41fa-978d-ac1e61e60786)
![1726714530809](https://github.com/user-attachments/assets/11a2ee1d-250b-4c4e-81f7-209f4dddf9d8)

**Comment by neverbiasu** [comment]
I suppose these images is generated by AI, which has insufficient edge detail between foreground and background.

**Comment by Young-Chin** [comment]
I agree with you that it might be one of the reasons. However, I tried another model [ComfyUI-BRIA_AI-RMBG](https://github.com/ZHO-ZHO-ZHO/ComfyUI-BRIA_AI-RMBG), which gives a smooth edge. So, there are potential problems with SAM and SAM2 when dealing with such cases.
