### ISSUE TITLE
syntax error in node.py

### ISSUE THREAD

**Issue by cyrille-g** [neverbiasu/ComfyUI-SAM2#27]
When installing the node in comfyUI, it throws an error on node.py line 38. 

there is a missing colon on line 40 : 

```
    "sam2_hiera_large.pt": {
        "model_url": "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt"
    }  <-- missing colon here
    "sam2_1_hiera_tiny": {

```

**Comment by camoody1** [comment]
> When installing the node in comfyUI, it throws an error on node.py line 38.
> 
> there is a missing colon on line 40 :
> 
> ```
>     "sam2_hiera_large.pt": {
>         "model_url": "https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_large.pt"
>     }  <-- missing colon here
>     "sam2_1_hiera_tiny": {
> ```

I think it's a missing comma, actually. 😁

**Comment by neverbiasu** [comment]
thanks, a syntax mistake
