### ISSUE TITLE
only have sam2.yaml, have not sam2.1.yaml

### ISSUE THREAD

**Issue by JohnsonXi** [neverbiasu/ComfyUI-SAM2#35]
Cannot find primary config 'sam2.yaml'. Check that it's in your config search path. Could you add auto-download yaml like load_groundingdino when firstly run load_sam
<img width="373" alt="image" src="https://github.com/user-attachments/assets/a25f1fae-2116-450d-a803-ccf3f4be1b84">

**Comment by neverbiasu** [comment]
solved in [commit](https://github.com/neverbiasu/ComfyUI-SAM2/commit/89d73e9b90c41722e3a67be3301171f5b3eb47dd)
