### ISSUE TITLE
axes don't match array

### ISSUE THREAD

**Issue by Yuliucheng** [neverbiasu/ComfyUI-SAM2#5]
Error occurred when executing GroundingDinoSAMSegment (segment anything):

axes don't match array

File "/tmp/code/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/tmp/code/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/tmp/code/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/tmp/code/ComfyUI/custom_nodes/ComfyUI-SAM2/node.py", line 311, in main
(images, masks) = sam_segment(
File "/tmp/code/ComfyUI/custom_nodes/ComfyUI-SAM2/node.py", line 238, in sam_segment
masks = np.transpose(masks, (1, 0, 2, 3))
File "/opt/conda/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 655, in transpose
return _wrapfunc(a, 'transpose', axes)
File "/opt/conda/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
return bound(*args, **kwds)
![Uploading 2024828501.png…]()

**Comment by Yuliuchengyin** [comment]
![Uploading 2024828501.png…]()

**Comment by neverbiasu** [comment]
Could you provide the mask details by `print("mask: ", mask)` before the line 238 in node.py.

**Comment by talhadar90** [comment]
I am facing the same issue

**Comment by neverbiasu** [comment]
My mistake, it should be `print("masks: ", masks)` instead of `print("mask: ", mask)`

**Comment by Yuliuchengyin** [comment]
I  Input it before ` masks = np.transpose(masks, (1, 0, 2, 3))` . The result is as follows: 

`Prompt executed in 15.56 seconds
got prompt
For numpy array image, we assume (HxWxC) format
Computing image embeddings for the provided image...
Image embeddings computed.
!!! Exception during processing!!! local variable 'mask' referenced before assignment
Traceback (most recent call last):
  File "/tmp/code/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/tmp/code/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/tmp/code/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/tmp/code/ComfyUI/custom_nodes/ComfyUI-SAM2/node.py", line 324, in main
  File "/tmp/code/ComfyUI/custom_nodes/ComfyUI-SAM2/node.py", line 242, in sam_segment
UnboundLocalError: local variable 'mask' referenced before assignment`

I run Comfyui in ubuntu22.04 
and  requirements versions are.  : 
cuda12.1.0
timm version: 1.0.7
addict version: 2.4.0
yapf version: 0.40.2
torch version: 2.3.1+cu121
torchvision version: 0.18.1+cu121
numpy version: 1.25.2
tqdm version: 4.66.4
iopath version: 0.1.10
matplotlib version: 3.9.1
opencv-python version: 4.8.0

**Comment by neverbiasu** [comment]
> My mistake, it should be `print("masks: ", masks)` instead of `print("mask: ", mask)`

`print("masks: ", masks)`use this

**Comment by Yuliuchengyin** [comment]
Of course, this is the result of `print("masks: ", masks)`   
![202483153346](https://github.com/user-attachments/assets/eb5079ba-728b-4deb-8b48-f352db32c65

**Comment by Yuliuchengyin** [comment]
![202483153346_副本](https://github.com/user-attachments/assets/e4371afc-53d2-44bc-b863-4cbf330404ca)

**Comment by neverbiasu** [comment]
let me check it, r u using autodl?

**Comment by Yuliuchengyin** [comment]
I gave up. It should be a system compatibility issue. Thank you very much for your patient answer😊. It's not autodl, but just a old and unknown cloud server

**Comment by neverbiasu** [comment]
U r welcome, I'm not a expert of ComfyUI, but more familiar with gradio. I might make a webui for SAM2, I will notify u if u r interested.

**Comment by Kostafun** [comment]
Hi, I got the same error, output with printing masks:

---cut---
Loaded checkpoint sucessfully
final text_encoder_type: bert-base-uncased
For numpy array image, we assume (HxWxC) format
Computing image embeddings for the provided image...
Image embeddings computed.
scores:  [     0.9913]
masks:  [[[          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  ...
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]
  [          0           0           0 ...           0           0           0]]]
!!! Exception during processing!!! axes don't match array
Traceback (most recent call last):
  File "/home/kostafun/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kostafun/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kostafun/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kostafun/ComfyUI/custom_nodes/ComfyUI-SAM2/node.py", line 312, in main
    (images, masks) = sam_segment(
                      ^^^^^^^^^^^^
  File "/home/kostafun/ComfyUI/custom_nodes/ComfyUI-SAM2/node.py", line 239, in sam_segment
    masks = np.transpose(masks, (1, 0, 2, 3))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kostafun/miniconda3/envs/comfyui/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 655, in transpose
    return _wrapfunc(a, 'transpose', axes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kostafun/miniconda3/envs/comfyui/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: axes don't match array
---cut---

**Comment by Kostafun** [comment]
It is working with square image.

**Comment by qiqiApink** [comment]
> I gave up. It should be a system compatibility issue. Thank you very much for your patient answer😊. It's not autodl, but just a old and unknown cloud server

You should delete the `squeeze(0)` in SAM2ImagePredictor.predict (line 280 - line 282 in ComfyUI-SAM2/sam2/sam2_image_predictor.py). Then it will works!

**Comment by JinshuChen** [comment]
> > I gave up. It should be a system compatibility issue. Thank you very much for your patient answer😊. It's not autodl, but just a old and unknown cloud server
> 
> @Yuliuchengyin You should delete the `squeeze(0)` in SAM2ImagePredictor.predict (line 280 - line 282 in ComfyUI-SAM2/sam2/sam2_image_predictor.py). Then it will works!

It does work ^^ and I strongly hope @neverbiasu could merge this fix into the default branch

**Comment by Nabby109** [comment]
I'm still getting this exact issue. My output looks basically just like Kosta's. But I'm using a square 1024x1024 image and checked the code and the squeeze command isn't in there so I'm current.

**Comment by Lucascuibu** [comment]
I delete all three `squeeze(0)`s mentioned above and it didnt work.

Then I asked deepseek and it asked me to  

replace `# masks = np.transpose(masks, (1, 0, 2, 3))`

with  `masks = np.expand_dims(masks, axis=0)`

and it worked! Hope it helps you.
