### ISSUE TITLE
ComfyUI SAM2(Segment Anything 2) install failed: With the current security level configuration, only custom nodes from the "default channel" can be installed.

### ISSUE THREAD

**Issue by gitnetworker21** [neverbiasu/ComfyUI-SAM2#8]
ComfyUI SAM2(Segment Anything 2) install failed: With the current security level configuration, only custom nodes from the "default channel" can be installed.

**Comment by neverbiasu** [comment]
That sounds like a comfyui manager issue, I haven't push my node to it. U can try to download with command `git clone https://github.com/neverbiasu/ComfyUI-SAM2` in your custom nodes folder.
