### ISSUE TITLE
help me , thank you

### ISSUE THREAD

**Issue by alexlaushing** [neverbiasu/ComfyUI-SAM2#9]
<img width="589" alt="PixPin_2024-08-04_23-21-04" src="https://github.com/user-attachments/assets/1294584b-7ee4-479d-9e9b-44e38c3059be">

**Comment by neverbiasu** [comment]
Actually, u r using the comfyui-segment-anything. Try to install this node by running `git clone https://github.com/neverbiasu/ComfyUI-SAM2` in custom_nodes folder.
